# yml file from Hadley: <https://github.com/hadley/r4ds/blob/main/_quarto.yml>

project:
  type: book
  output-dir: _book

bibliography: lessons_original/bib/packages.bib

book:
  title: "An R Cookbook for Public Health"
  subtitle: "Course Materials for PHC 6099: 'R Computing for Health Sciences'"
  collection-editor: "Gabriel J. Odom, PhD, ThD"
  reader-mode: true

  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  site-url: https://gabrielodom.github.io/PHC6099_rBiostat/
  repo-url: https://github.com/gabrielodom/PHC6099_rBiostat
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - about.qmd

    - part: 01_header_EDA.qmd
      chapters:
        - lessons/01_mosaic_violin.qmd
        - lessons/01_scatterplots.qmd
        - lessons_original/01_skimr.qmd
        - lessons/01_table1.qmd
        - lessons/01_gtsummary.qmd
        # - lessons_original/01_rayshader.qmd

    - part: 02_header_one-sample.qmd
      chapters:
        - lessons/02_z-test_one_prop.qmd
        - lessons/02_wilcoxon_one_samp.qmd
        - lessons/02_mcnemar_paired_samp.qmd
        - lessons/02_chiSq_GoF.qmd
        - lessons/02_transformations.qmd
        - lessons/02_fisher_exact_test.qmd

    - part: 03_header_two-sample.qmd
      chapters:
        - lessons_original/03_two_sample_ttest.qmd
        - lessons/03_two_sample_mann_whitney.qmd
        - lessons/03_two_sample_bootstrap_conf_int.qmd
        - lessons_original/03_two_sample_chi_sq_independence.qmd

    - part: 04_header_anova-and-regression.qmd
      chapters:
        - lessons/04_anova_one_way.qmd
        - lessons_original/04_anova_two_way.qmd
        - lessons_original/04_anova_kruskal_wallis.qmd
        - lessons_original/04_anova_random_intercept.qmd
        - lessons/04_corr_cov.qmd
        - lessons_original/04_regression_ols.qmd
        - lessons_original/04_regression_mls.qmd
        - lessons_original/04_regression_polynomial.qmd

    - part: 05_header_generalized-linear-models.qmd
      chapters:
        - lessons_original/05_glm_ordinal_logistic.qmd

    - part: 06_header_special-topics.qmd
      chapters:
        - lessons/06_lesson_template_spec_topc.qmd

    - part: 07_header_power.qmd
      chapters:
        - lessons_original/07_power_ols.qmd

format:
  html:
    theme:
      - cosmo
      - styles.scss
    code-link: true
    author-meta: "Gabriel Odom"
    callout-appearance: simple
