<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.553">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="author" content="Gabriel Odom">
<title>An R Cookbook for Public Health - 23&nbsp; Welch’s Anova</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../lessons_original/04_anova_kruskal_wallis.html" rel="next">
<link href="../lessons/04_anova_two_way.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../04_header_anova-and-regression.html">ANOVA and Regression</a></li><li class="breadcrumb-item"><a href="../lessons/04_anova_welch_two_way.html"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Welch’s Anova</span></a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">An R Cookbook for Public Health</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/gabrielodom/PHC6099_rBiostat" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Course Materials for PHC 6099: ‘R Computing for Health Sciences’</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../about.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">About this Book</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../01_header_EDA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exploratory Data Analysis</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lessons/01_mosaic_violin.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Mosaic &amp; Box/Violin Plots</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lessons/01_scatterplots.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">How to Create a Scatterplot</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lessons_original/01_skimr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Skimr Package</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lessons/01_table1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Demographics Table With Table1</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lessons/01_gtsummary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Table by gtsummary</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../02_header_one-sample.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">One-Sample Tests</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lessons/02_z-test_one_prop.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Z-Test for One Proportion</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lessons/02_ttest_one_samp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">One-sample/paired t-test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lessons/02_wilcoxon_one_samp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Wilcoxon Signed Rank Test for One Sample</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lessons/02_mcnemar_paired_samp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">McNemar’s Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lessons/02_cochrans_q_paired_samp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Cochran’s Q Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lessons/02_chiSq_GoF.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">The Chi Squared Goodness-of-Fit Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lessons/02_transformations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Transformations to Normality</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lessons/02_fisher_exact_test.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Fisher’s Exact Test</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../03_header_two-sample.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Two-Sample Tests</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lessons/03_two_sample_ttest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Two sample <span class="math inline">\(t\)</span>-test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lessons/03_two_sample_welch_ttest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Two sample Welchs test or Welchs t-test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lessons/03_two_sample_mann_whitney.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Mann-Whitney-U Test Example</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lessons/03_two_sample_bootstrap_conf_int.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Bootstrap Tests</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lessons/03_two_sample_chi_sq_independence.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Chi-Square Test of Independence</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../04_header_anova-and-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ANOVA and Regression</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lessons/04_anova_one_way.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">One-Way ANOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lessons/04_anova_two_way.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Two-Way ANOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lessons/04_anova_welch_two_way.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Welch’s Anova</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lessons_original/04_anova_kruskal_wallis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Non-Parametric ANOVA: The Kruskal-Wallis Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lessons/04_anova_random_intercept.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Repeated Measures ANOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lessons/04_corr_cov.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Correlation and Covariance Matrices</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lessons_original/04_regression_ols.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Ordinary Least Squares Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lessons/04_regression_mls.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Multiple Linear Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lessons/04_regression_polynomial.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Introduction to Polynomial Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lessons_original/04_regression_random_intercept.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Random Intercept Regression</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../05_header_generalized-linear-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Generalized Linear Models</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lessons/05_glm_logistic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Generalized Linear Models for Binary Response</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lessons/05_glm_ordinal_logistic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Ordinal Logistic Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lessons/05_glm_poisson.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Poisson Regression Model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lessons/05_glm_negative_binomial.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Generalized Linear Models: Negative Binomial</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../06_header_special-topics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Special Topics in Statistical Modelling</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lessons/06_elastic_net_regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Elastic Net Regression Model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lessons/06_survival_analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Survival Analysis in R</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../07_header_power.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Statistical Power and Sample Size Determination</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lessons_original/07_power_ols.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Power Analysis for OLS Regression</span></span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li><a href="#packages-for-this-lesson" id="toc-packages-for-this-lesson" class="nav-link active" data-scroll-target="#packages-for-this-lesson"><span class="header-section-number">23.1</span> Packages for this lesson</a></li>
  <li>
<a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction"><span class="header-section-number">23.2</span> Introduction</a>
  <ul class="collapse">
<li><a href="#when-to-use-welchs-anova" id="toc-when-to-use-welchs-anova" class="nav-link" data-scroll-target="#when-to-use-welchs-anova"><span class="header-section-number">23.2.1</span> When to use Welch´s Anova</a></li>
  </ul>
</li>
  <li><a href="#assumptions-of-welchs-anova" id="toc-assumptions-of-welchs-anova" class="nav-link" data-scroll-target="#assumptions-of-welchs-anova"><span class="header-section-number">23.3</span> Assumptions of Welch´s Anova</a></li>
  <li><a href="#comparison-of-traditional-anova-and-welchs-anova" id="toc-comparison-of-traditional-anova-and-welchs-anova" class="nav-link" data-scroll-target="#comparison-of-traditional-anova-and-welchs-anova"><span class="header-section-number">23.4</span> Comparison of Traditional ANOVA and Welch’s ANOVA</a></li>
  <li>
<a href="#reliability-of-welchs-anova" id="toc-reliability-of-welchs-anova" class="nav-link" data-scroll-target="#reliability-of-welchs-anova"><span class="header-section-number">23.5</span> Reliability of Welch’s ANOVA</a>
  <ul class="collapse">
<li><a href="#lets-remember" id="toc-lets-remember" class="nav-link" data-scroll-target="#lets-remember"><span class="header-section-number">23.5.1</span> Let’s Remember</a></li>
  <li><a href="#suspecting-different-variances" id="toc-suspecting-different-variances" class="nav-link" data-scroll-target="#suspecting-different-variances"><span class="header-section-number">23.5.2</span> Suspecting Different Variances:</a></li>
  <li><a href="#assessing-normality" id="toc-assessing-normality" class="nav-link" data-scroll-target="#assessing-normality"><span class="header-section-number">23.5.3</span> Assessing normality:</a></li>
  </ul>
</li>
  <li><a href="#defyning-the-question-and-hypotheses" id="toc-defyning-the-question-and-hypotheses" class="nav-link" data-scroll-target="#defyning-the-question-and-hypotheses"><span class="header-section-number">23.6</span> Defyning the question and hypotheses</a></li>
  <li><a href="#dataset-visualization" id="toc-dataset-visualization" class="nav-link" data-scroll-target="#dataset-visualization"><span class="header-section-number">23.7</span> Dataset visualization</a></li>
  <li>
<a href="#plotting-mtcars-data" id="toc-plotting-mtcars-data" class="nav-link" data-scroll-target="#plotting-mtcars-data"><span class="header-section-number">23.8</span> Plotting Mtcars data</a>
  <ul class="collapse">
<li><a href="#assessing-the-distribution" id="toc-assessing-the-distribution" class="nav-link" data-scroll-target="#assessing-the-distribution"><span class="header-section-number">23.8.1</span> Assessing the distribution</a></li>
  <li><a href="#assessing-skewness-and-kurtosis" id="toc-assessing-skewness-and-kurtosis" class="nav-link" data-scroll-target="#assessing-skewness-and-kurtosis"><span class="header-section-number">23.8.2</span> Assessing skewness and kurtosis</a></li>
  <li><a href="#normality-test" id="toc-normality-test" class="nav-link" data-scroll-target="#normality-test"><span class="header-section-number">23.8.3</span> Normality test</a></li>
  </ul>
</li>
  <li>
<a href="#performing-the-welchs-anova" id="toc-performing-the-welchs-anova" class="nav-link" data-scroll-target="#performing-the-welchs-anova"><span class="header-section-number">23.9</span> Performing the Welchs Anova</a>
  <ul class="collapse">
<li><a href="#welchs-anova-results" id="toc-welchs-anova-results" class="nav-link" data-scroll-target="#welchs-anova-results"><span class="header-section-number">23.9.1</span> Welchs Anova results</a></li>
  <li><a href="#interpretation-or-results" id="toc-interpretation-or-results" class="nav-link" data-scroll-target="#interpretation-or-results"><span class="header-section-number">23.9.2</span> Interpretation or results:</a></li>
  </ul>
</li>
  <li>
<a href="#satterthwaite-degrees-of-freedom" id="toc-satterthwaite-degrees-of-freedom" class="nav-link" data-scroll-target="#satterthwaite-degrees-of-freedom"><span class="header-section-number">23.10</span> Satterthwaite Degrees of Freedom</a>
  <ul class="collapse">
<li><a href="#degrees-of-freedom-dof-explanation" id="toc-degrees-of-freedom-dof-explanation" class="nav-link" data-scroll-target="#degrees-of-freedom-dof-explanation"><span class="header-section-number">23.10.1</span> Degrees of Freedom (DoF) explanation:</a></li>
  <li><a href="#important-concepts-about-the-degrees-of-freedom" id="toc-important-concepts-about-the-degrees-of-freedom" class="nav-link" data-scroll-target="#important-concepts-about-the-degrees-of-freedom"><span class="header-section-number">23.10.2</span> Important concepts about the degrees of Freedom</a></li>
  </ul>
</li>
  <li><a href="#summary-and-conclusion" id="toc-summary-and-conclusion" class="nav-link" data-scroll-target="#summary-and-conclusion"><span class="header-section-number">23.11</span> Summary and Conclusion</a></li>
  </ul><div class="toc-actions"><ul><li><a href="https://github.com/gabrielodom/PHC6099_rBiostat/edit/main/lessons/04_anova_welch_two_way.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/gabrielodom/PHC6099_rBiostat/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../04_header_anova-and-regression.html">ANOVA and Regression</a></li><li class="breadcrumb-item"><a href="../lessons/04_anova_welch_two_way.html"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Welch’s Anova</span></a></li></ol></nav><div class="quarto-title">
<h1 class="title">
<span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Welch’s Anova</span>
</h1>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Author</div>
  <div class="quarto-title-meta-heading">Affiliations</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Guillermo Andres Rodriguez Rondón </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Florida International University
          </p>
        <p class="affiliation">
            Robert Stempel School of Public Health
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
  
    
  </div>
  


</header><section id="packages-for-this-lesson" class="level2" data-number="23.1"><h2 data-number="23.1" class="anchored" data-anchor-id="packages-for-this-lesson">
<span class="header-section-number">23.1</span> Packages for this lesson</h2>
<p>We will need to load tidyverse (which contains <code>ggplot2</code>, <code>dplyr</code> and <code>tibble</code>), gridExtra, emmeans and e1071. We are going to use the <code>mtcars</code> dataset included in r studio.</p>
</section><section id="introduction" class="level2" data-number="23.2"><h2 data-number="23.2" class="anchored" data-anchor-id="introduction">
<span class="header-section-number">23.2</span> Introduction</h2>
<p><strong>Welch’s ANOVA, an extension of Welch’s t-test, is designed to compare the means of three or more groups when the assumption of equal variances (homoscedasticity) is violated</strong>. Unlike the traditional ANOVA, which assumes that the variances across groups are equal, Welch’s ANOVA is robust to heteroscedasticity, making it more reliable when dealing with real-world data that often exhibit unequal variances.</p>
<p>This statistical method is particularly useful in fields such as biology, medicine, and social sciences, where differences in group variances are common. By adjusting the degrees of freedom and using a modified F-ratio, Welch’s ANOVA provides a more accurate p-value for hypothesis testing under these conditions. This adaptation enhances the validity of the conclusions drawn from the data, ensuring that the results are not unduly influenced by variance inequality <span class="citation" data-cites="Liu2015-xy">(<a href="#ref-Liu2015-xy" role="doc-biblioref">Liu, 2015a</a>)</span></p>
<section id="when-to-use-welchs-anova" class="level3" data-number="23.2.1"><h3 data-number="23.2.1" class="anchored" data-anchor-id="when-to-use-welchs-anova">
<span class="header-section-number">23.2.1</span> When to use Welch´s Anova</h3>
<p>Welch’s ANOVA is particularly useful in the following scenarios:</p>
<p><strong>Unequal Variances (Heteroscedasticity):</strong></p>
<p>When the variances across the groups being compared are not equal, Welch’s ANOVA should be used. Traditional ANOVA assumes homoscedasticity (equal variances), and when this assumption is violated, it can lead to inaccurate results. Welch’s ANOVA adjusts for unequal variances, providing more reliable results <span class="citation" data-cites="Delacre2019-ra">(<a href="#ref-Delacre2019-ra" role="doc-biblioref">Delacre, Leys, Mora, &amp; Lakens, 2019</a>)</span>.</p>
<p><strong>Unequal Sample Sizes:</strong></p>
<p>When the groups have different sample sizes, Welch’s ANOVA is more appropriate. Traditional ANOVA is sensitive to unequal sample sizes, especially when combined with unequal variances. Welch’s ANOVA is robust to these differences, ensuring that the statistical conclusions remain valid <span class="citation" data-cites="Delacre2019-ra">(<a href="#ref-Delacre2019-ra" role="doc-biblioref">Delacre et al., 2019</a>)</span>.</p>
<p><strong>Comparing Means of Three or More Groups:</strong></p>
<p>Similar to the traditional ANOVA, Welch’s ANOVA is used when you need to compare the means of three or more groups. It extends the principles of Welch’s t-test (which compares two groups) to multiple groups <span class="citation" data-cites="Delacre2019-ra">(<a href="#ref-Delacre2019-ra" role="doc-biblioref">Delacre et al., 2019</a>)</span>.</p>
<p><strong>Real-World Data with Variability:</strong></p>
<p>In practical applications, data often do not meet the strict assumptions of equal variances and equal sample sizes. Welch’s ANOVA is more flexible and can handle the variability often found in real-world data, making it a preferred choice in many applied research settings.</p>
<p><strong>Increased Reliability:</strong></p>
<p>When you require a statistical test that remains robust under less-than-ideal conditions, such as non-normal distributions and unequal group variances, Welch’s ANOVA provides increased reliability and accuracy compared to traditional ANOVA <span class="citation" data-cites="Delacre2019-ra">(<a href="#ref-Delacre2019-ra" role="doc-biblioref">Delacre et al., 2019</a>)</span>.</p>
<p><strong>Practical Examples</strong></p>
<p><strong>Medical Research:</strong> Comparing the effectiveness of different treatments across patient groups where the variance in treatment effects is different.</p>
<p><strong>Educational Studies:</strong> Analyzing test scores from students in different schools or classes where the variability in scores differs.</p>
<p><strong>Biological Experiments:</strong> Evaluating the growth of plants under different treatments when the growth variability is not consistent across treatments.</p>
<p>By using Welch’s ANOVA in these scenarios, researchers can ensure their statistical analyses are valid and robust, leading to more accurate and trustworthy conclusions.</p>
</section></section><section id="assumptions-of-welchs-anova" class="level2" data-number="23.3"><h2 data-number="23.3" class="anchored" data-anchor-id="assumptions-of-welchs-anova">
<span class="header-section-number">23.3</span> Assumptions of Welch´s Anova</h2>
<p>Welch’s ANOVA, like any statistical test, has specific assumptions that need to be met to ensure valid and reliable results. However, it relaxes some of the assumptions required by traditional ANOVA, making it more robust to real-world data. Here are the key assumptions of Welch’s ANOVA:</p>
<p><strong>Independence of Observations:</strong></p>
<p>The observations within each group and between groups should be independent. This means that the data points collected from different groups do not influence each other.</p>
<p><strong>Normality:</strong></p>
<p>The dependent variable should be approximately normally distributed within each group. Welch’s ANOVA is fairly robust to deviations from normality, especially with larger sample sizes. However, significant departures from normality can affect the results, so it’s important to assess the distribution of the data.</p>
<p><strong>Unequal Variances:</strong></p>
<p>Unlike traditional ANOVA, Welch’s ANOVA does not assume equal variances across groups. It is specifically designed to handle heteroscedasticity (unequal variances) by adjusting the degrees of freedom and modifying the F-ratio. This makes Welch’s ANOVA more appropriate when the homogeneity of variances assumption is violated.<span class="citation" data-cites="Liu2015-ql">(<a href="#ref-Liu2015-ql" role="doc-biblioref">Liu, 2015b</a>)</span>.</p>
<p>The formula for the Welch’s anova is given by:</p>
<p><span class="math display">\[
F = \frac{\sum_{i=1}^{k} \frac{n_i (\bar{X}_i - \bar{X})^2}{s_i^2}}{1 + \frac{2(k-2)}{k^2 - 1} \sum_{i=1}^{k} \left( \frac{1}{n_i - 1} \right) \left( \frac{s_i^2}{s_{avg}^2} \right)^2 }
\]</span></p>
<p>Where: <span class="math display">\[\begin{align*}
\bar{X}_i &amp; \text{ is the sample mean of the i-th group} \\
\bar{X} &amp; \text{ is the grand mean (overall mean)} \\
n_i &amp; \text{ is the sample size of the i-th group} \\
s_i^2 &amp; \text{ is the sample variance of the i-th group} \\
s_{avg}^2 &amp; \text{ is the average of the sample variances, } s_{avg}^2 = \frac{1}{k} \sum_{i=1}^{k} s_i^2 \\
k &amp; \text{ is the number of groups}
\end{align*}\]</span></p>
<p>The degrees of freedom for the numerator and the denominator are given by <span class="citation" data-cites="Liu2015-ql">(<a href="#ref-Liu2015-ql" role="doc-biblioref">Liu, 2015b</a>)</span>:</p>
<p><span class="math display">\[
\text{df}_1 = k - 1
\]</span></p>
<p><span class="math display">\[
\text{df}_2 = \frac{ \left( 1 + \frac{2(k-2)}{k^2 - 1} \sum_{i=1}^{k} \left( \frac{1}{n_i - 1} \right) \left( \frac{s_i^2}{s_{avg}^2} \right)^2 \right)^2 }{ \frac{2(k-2)}{k^2 - 1} \sum_{i=1}^{k} \left( \frac{1}{(n_i - 1)^2} \right) \left( \frac{s_i^2}{s_{avg}^2} \right)^2 }
\]</span></p>
</section><section id="comparison-of-traditional-anova-and-welchs-anova" class="level2" data-number="23.4"><h2 data-number="23.4" class="anchored" data-anchor-id="comparison-of-traditional-anova-and-welchs-anova">
<span class="header-section-number">23.4</span> Comparison of Traditional ANOVA and Welch’s ANOVA</h2>
<p>Welch’s ANOVA and traditional ANOVA are both used to compare the means of three or more groups, but they have different assumptions and are suitable for different scenarios. Here’s a detailed comparison:</p>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Comparison Summary
</div>
</div>
<div class="callout-body-container callout-body">
<table class="table">
<colgroup>
<col style="width: 8%">
<col style="width: 46%">
<col style="width: 44%">
</colgroup>
<thead><tr class="header">
<th>Aspect</th>
<th>Traditional ANOVA</th>
<th>Welch’s ANOVA</th>
</tr></thead>
<tbody>
<tr class="odd">
<td><strong>Assumptions</strong></td>
<td>Equal Variances (Homoscedasticity): Assumes that the variances across groups are equal.<br>Normality: Assumes that the data within each group are normally distributed.<br>Independence: Assumes that the observations are independent of each other.</td>
<td>Unequal Variances (Heteroscedasticity): Does not assume equal variances across groups, making it suitable for data with heteroscedasticity.<br>Normality: Assumes that the data within each group are normally distributed, similar to traditional ANOVA.<br>Independence: Assumes that the observations are independent of each other.</td>
</tr>
<tr class="even">
<td><strong>Robustness to Assumptions</strong></td>
<td>Sensitive to Unequal Variances: If the assumption of equal variances is violated, the results of traditional ANOVA can be misleading.<br>Robust to Normality: Fairly robust to deviations from normality, especially with larger sample sizes (Liu, 2015b).</td>
<td>Robust to Unequal Variances: Specifically designed to handle unequal variances, providing more reliable results when variances differ across groups.<br>Robust to Normality: Similar robustness to normality as traditional ANOVA, but still requires approximate normality within groups (Liu, 2015b).</td>
</tr>
<tr class="odd">
<td><strong>Degrees of Freedom</strong></td>
<td>Degrees of freedom for the numerator (df1) is k-1, where k is the number of groups.<br>Degrees of freedom for the denominator (df2) is N-k, where N is the total number of observations (Liu, 2015b).</td>
<td>Degrees of freedom for the numerator (df1) is k-1, similar to traditional ANOVA.<br>Degrees of freedom for the denominator (df2) is adjusted based on the variances and sample sizes of the groups, making it more complex and generally lower than N-k (Liu, 2015b).</td>
</tr>
<tr class="even">
<td><strong>Application Scenarios</strong></td>
<td>Use when you have equal variances across groups and possibly equal sample sizes. Suitable for controlled experimental designs where assumptions can be maintained.</td>
<td>Use when variances across groups are unequal or when sample sizes are unequal. Suitable for real-world data where assumptions of traditional ANOVA are often violated.</td>
</tr>
</tbody>
</table>
</div>
</div>
</section><section id="reliability-of-welchs-anova" class="level2" data-number="23.5"><h2 data-number="23.5" class="anchored" data-anchor-id="reliability-of-welchs-anova">
<span class="header-section-number">23.5</span> Reliability of Welch’s ANOVA</h2>
<p>Welch’s ANOVA is designed to be a robust alternative to traditional ANOVA, particularly when dealing with unequal variances across groups. Here’s a detailed look at factors affecting the reliability of Welch’s ANOVA, including minimum sample size, power, effect size, variance, significance level, and non-normality.</p>
<p><strong>1. Minimum Sample Size</strong></p>
<p>Small Sample Sizes: Welch’s ANOVA can be used with small sample sizes, but its power is limited with very small samples (e.g., fewer than 5 observations per group). In such cases, the test might not detect significant differences even if they exist.</p>
<p>Recommended Minimum: A common recommendation is to have at least 10-15 observations per group. This ensures a reasonable level of reliability and power. This isn’t a strict rule but a guideline to aim for.</p>
<p><strong>2. Power and Effect Size</strong></p>
<p>Power Analysis: Power is the probability of correctly rejecting the null hypothesis when it is false. To determine the appropriate sample size for a specific context, you can perform a power analysis. This involves specifying the expected effect size, the desired power (commonly 0.80), and the significance level (commonly 0.05).</p>
<p>Effect Size: Larger effect sizes (i.e., larger differences between group means) can be detected with smaller sample sizes. Smaller effect sizes require larger sample sizes to be detected. Power analysis can help estimate the necessary sample size to achieve sufficient power to detect an effect.</p>
<p><strong>3. Variance</strong></p>
<p>Unequal Variances: Welch’s ANOVA is specifically designed to handle unequal variances. It adjusts the degrees of freedom and uses a modified F-ratio to account for this heteroscedasticity, providing more accurate p-values.</p>
<p>Large Variance Differences: When variances between groups are very different, larger sample sizes may be needed to ensure the robustness of the test.</p>
<p><strong>4. Significance Level</strong></p>
<p>Common Significance Levels: The significance level (α) is the threshold for determining statistical significance, with common values being 0.05, 0.01, and 0.10.</p>
<p>Impact of Significance Level: Lowering the significance level (e.g., from 0.05 to 0.01) makes the test more stringent, reducing the chance of Type I errors (false positives). However, this typically requires larger sample sizes to maintain power.</p>
<p>Type I and Type II Errors: Balancing the significance level and power is crucial to minimize both Type I errors (incorrectly rejecting the null hypothesis) and Type II errors (failing to reject a false null hypothesis).</p>
<p><strong>5. Non-Normality</strong></p>
<p>Moderate Robustness: Welch’s ANOVA is moderately robust to deviations from normality, especially as sample sizes increase. This robustness is due to the Central Limit Theorem, which ensures that the sampling distribution of the test statistic approaches normality with larger sample sizes.</p>
<p>Severe Non-Normality: For small sample sizes, significant departures from normality can affect the reliability of Welch’s ANOVA. In such cases, the test may not perform well, and the results might be less trustworthy.</p>
<p><strong>Alternative Approaches:</strong> When normality is a concern, consider non-parametric alternatives like the <strong>Kruskal-Wallis test</strong>, which does not assume normality.</p>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Guidelines for Choosing Welch’s ANOVA or Kruskal-Wallis Test
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>
<strong>Uses Welch’s ANOVA</strong> if all sample sizes are ≥ 30 or Shapiro-Wilk test is ≥ 0.05 (normal distribution).</li>
<li>
<strong>Uses Welch’s ANOVA</strong> if all sample sizes are ≥ 15 and the p-values from the Shapiro-Wilk test are &gt; 0.01 (indicating only moderate deviations from normality).</li>
<li>
<strong>Uses the Kruskal-Wallis test</strong> if any sample size is &lt; 15 or if the p-values from the Shapiro-Wilk test are ≤ 0.01 (indicating severe deviations from normality).</li>
</ul>
</div>
</div>
<p><strong>Practical Recommendations:</strong></p>
<p>Assess Normality and Variance: Before applying Welch’s ANOVA, assess the normality and variances of your data. Use tests like Shapiro-Wilk for normality and Levene’s test for variance homogeneity. Perform Power Analysis: Conduct a power analysis to determine the appropriate sample size for your study, considering the expected effect size and desired power. Consider Sample Size Guidelines: Aim for at least 10-15 observations per group to ensure reasonable power and reliability.</p>
<section id="lets-remember" class="level3" data-number="23.5.1"><h3 data-number="23.5.1" class="anchored" data-anchor-id="lets-remember">
<span class="header-section-number">23.5.1</span> Let’s Remember</h3>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Let’s remember
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>The significance level</strong>, denoted as α, is a threshold in hypothesis testing that determines whether to reject the null hypothesis. <strong>It is the probability of making a Type I error</strong>, which occurs when the null hypothesis is true but incorrectly rejected. Common values for α are 0.05, 0.01, and 0.10 <span class="citation" data-cites="Labovitz2017-yp">(<a href="#ref-Labovitz2017-yp" role="doc-biblioref">Labovitz, 2017</a>)</span>.</p>
<p>For α = 0.05, there is a 5% chance of rejecting the null hypothesis when it is true. If the p-value from a statistical test is less than or equal to α, we reject the null hypothesis; if it is greater, we do not reject the null hypothesis.</p>
<p><strong>The Central Limit Theorem (CLT)</strong> states that the distribution of the sample mean will approximate a normal distribution as the sample size becomes large, regardless of the population’s distribution, provided the samples are independent and identically distributed <span class="citation" data-cites="Kwak2017-vr">(<a href="#ref-Kwak2017-vr" role="doc-biblioref">Kwak &amp; Kim, 2017</a>)</span>.</p>
<p>In the context of Welch’s test, the CLT implies that as the sample size increases, the distribution of the test statistic approaches normality, reducing the impact of non-normality in the original data. Thus, Welch’s test becomes more reliable with larger samples because the sampling distribution of the mean difference tends to be normal.</p>
<p><strong>If the samples are not identically distributed, meaning they come from populations with different distributions, the assumptions underlying the Central Limit Theorem (CLT) and many statistical tests, including Welch’s t-test, may be violated. This can have several consequences</strong>:</p>
<ul>
<li>
<strong>Reduced Accuracy</strong>: The approximation to the normal distribution for the sample mean may not hold, leading to inaccurate p-values and confidence intervals.</li>
<li>
<strong>Increased Type I and Type II Errors</strong>: There may be an increased risk of Type I errors (incorrectly rejecting a true null hypothesis) and Type II errors (failing to reject a false null hypothesis).</li>
<li>
<strong>Biased Results</strong>: The test results may be biased, reflecting the differences in the underlying distributions rather than the true differences between the population means <span class="citation" data-cites="ruxton2006unequal">(<a href="#ref-ruxton2006unequal" role="doc-biblioref">Ruxton, 2006</a>)</span>.</li>
</ul>
</div>
</div>
</section><section id="suspecting-different-variances" class="level3" data-number="23.5.2"><h3 data-number="23.5.2" class="anchored" data-anchor-id="suspecting-different-variances">
<span class="header-section-number">23.5.2</span> Suspecting Different Variances:</h3>
<p>You might suspect different variances when comparing groups (samples) and their spread appears noticeably different. For example, if one group’s data points are more dispersed than the others, it could indicate unequal variances.The welch´s Anova don´t need equal variances to perform well but you can asses variances with graphical methods and using the Levene´s test.</p>
</section><section id="assessing-normality" class="level3" data-number="23.5.3"><h3 data-number="23.5.3" class="anchored" data-anchor-id="assessing-normality">
<span class="header-section-number">23.5.3</span> Assessing normality:</h3>
<p><strong>Shapiro-Wilk Test</strong>: Purpose: Determines if a sample comes from a normally distributed population. Suitability for Small Samples: Good power even with small sample sizes (&lt; 50). How It Works: Compares the sample data to a normal distribution. Interpretation: If p-value &lt; chosen alpha level, data is not normally distributed. Advantages: Sensitive to deviations in both location and shape. Limitations: May detect trivial deviations due to large sample size1 <span class="citation" data-cites="Razali2011-aq">(<a href="#ref-Razali2011-aq" role="doc-biblioref">Razali &amp; Wah, 2011</a>)</span>.</p>
<p><strong>Kolmogorov-Smirnov (K-S) Test</strong>: Purpose: Compares two samples or tests if a sample matches a reference distribution. Suitability for Small Samples: Useful for small to large sample sizes. How It Works: Quantifies the distance between empirical and reference cumulative distribution functions. Interpretation: Compares observed data to expected distribution. Advantages: Sensitive to differences in both location and shape. Limitations: May not be better than Shapiro-Wilk for small samples <span class="citation" data-cites="Razali2011-aq">(<a href="#ref-Razali2011-aq" role="doc-biblioref">Razali &amp; Wah, 2011</a>)</span>.</p>
<p><strong>Anderson-Darling Test</strong>: Purpose: Tests if a sample comes from a specific distribution (e.g., normal). Suitability for Small Samples: Similar to Shapiro-Wilk. How It Works: Compares observed data to expected distribution. Interpretation: Reject null hypothesis if p-value &lt; chosen alpha level. Advantages: Generalizes well for various distributions. Limitations: Adjust for parameter estimation if needed <span class="citation" data-cites="Razali2011-aq">(<a href="#ref-Razali2011-aq" role="doc-biblioref">Razali &amp; Wah, 2011</a>)</span>.</p>
<p><strong>Graphical Inspection</strong>: Plot histograms or box plots for each group. Look for differences in spread!!</p>
</section></section><section id="defyning-the-question-and-hypotheses" class="level2" data-number="23.6"><h2 data-number="23.6" class="anchored" data-anchor-id="defyning-the-question-and-hypotheses">
<span class="header-section-number">23.6</span> Defyning the question and hypotheses</h2>
<p>Null hypothesis (H0): 4 cylinder cars, 6 cylinder cars and 8 cylinder cars have equal miles per galon (mpg) mean. Alternative hypothesis (HA): 4 cylinder cars, 6 cylinder cars and 8 cylinder cars have not equal miles per galon (mpg) mean.</p>
</section><section id="dataset-visualization" class="level2" data-number="23.7"><h2 data-number="23.7" class="anchored" data-anchor-id="dataset-visualization">
<span class="header-section-number">23.7</span> Dataset visualization</h2>
<p>We will use the <code>mtcars</code> dataset in R for this demonstration. This dataset contains various attributes of different car models and at priori we are not sure if the assumptions are meet, so we have to assess the data first:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   32 obs. of  11 variables:
 $ mpg : num  21 21 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 ...
 $ cyl : num  6 6 4 6 8 6 8 4 4 6 ...
 $ disp: num  160 160 108 258 360 ...
 $ hp  : num  110 110 93 110 175 105 245 62 95 123 ...
 $ drat: num  3.9 3.9 3.85 3.08 3.15 2.76 3.21 3.69 3.92 3.92 ...
 $ wt  : num  2.62 2.88 2.32 3.21 3.44 ...
 $ qsec: num  16.5 17 18.6 19.4 17 ...
 $ vs  : num  0 0 1 1 0 1 0 1 1 1 ...
 $ am  : num  1 1 1 0 0 0 0 0 0 0 ...
 $ gear: num  4 4 4 3 3 3 3 4 4 4 ...
 $ carb: num  4 4 1 1 2 1 4 2 2 4 ...</code></pre>
</div>
</div>
<p>As we can see, we have a data set with the information about different types of cars, with 11 different variables including miles per gallon (mpg), cylinder (cyl), horse power (hp), etc., and there are 32 observations for each variable.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>      mpg             cyl             disp             hp       
 Min.   :10.40   Min.   :4.000   Min.   : 71.1   Min.   : 52.0  
 1st Qu.:15.43   1st Qu.:4.000   1st Qu.:120.8   1st Qu.: 96.5  
 Median :19.20   Median :6.000   Median :196.3   Median :123.0  
 Mean   :20.09   Mean   :6.188   Mean   :230.7   Mean   :146.7  
 3rd Qu.:22.80   3rd Qu.:8.000   3rd Qu.:326.0   3rd Qu.:180.0  
 Max.   :33.90   Max.   :8.000   Max.   :472.0   Max.   :335.0  
      drat             wt             qsec             vs        
 Min.   :2.760   Min.   :1.513   Min.   :14.50   Min.   :0.0000  
 1st Qu.:3.080   1st Qu.:2.581   1st Qu.:16.89   1st Qu.:0.0000  
 Median :3.695   Median :3.325   Median :17.71   Median :0.0000  
 Mean   :3.597   Mean   :3.217   Mean   :17.85   Mean   :0.4375  
 3rd Qu.:3.920   3rd Qu.:3.610   3rd Qu.:18.90   3rd Qu.:1.0000  
 Max.   :4.930   Max.   :5.424   Max.   :22.90   Max.   :1.0000  
       am              gear            carb      
 Min.   :0.0000   Min.   :3.000   Min.   :1.000  
 1st Qu.:0.0000   1st Qu.:3.000   1st Qu.:2.000  
 Median :0.0000   Median :4.000   Median :2.000  
 Mean   :0.4062   Mean   :3.688   Mean   :2.812  
 3rd Qu.:1.0000   3rd Qu.:4.000   3rd Qu.:4.000  
 Max.   :1.0000   Max.   :5.000   Max.   :8.000  </code></pre>
</div>
</div>
</section><section id="plotting-mtcars-data" class="level2" data-number="23.8"><h2 data-number="23.8" class="anchored" data-anchor-id="plotting-mtcars-data">
<span class="header-section-number">23.8</span> Plotting Mtcars data</h2>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="04_anova_welch_two_way_files/figure-html/plot-counts-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Cars by gears and cylinders</figcaption></figure>
</div>
</div>
</div>
<p>On this bar graph we observe the count of cars by number of cylinders and gears.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="04_anova_welch_two_way_files/figure-html/plot-mtcars-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>mpg v.s hp</figcaption></figure>
</div>
</div>
</div>
<p>Just to give us an idea of the data set, on this plot we observed the relation between horse power and cylinders. The cars with more cylinders have more hp and probably do less miles per gallon.</p>
<section id="assessing-the-distribution" class="level3" data-number="23.8.1"><h3 data-number="23.8.1" class="anchored" data-anchor-id="assessing-the-distribution">
<span class="header-section-number">23.8.1</span> Assessing the distribution</h3>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: The `size` argument of `element_rect()` is deprecated as of ggplot2 3.4.0.
ℹ Please use the `linewidth` argument instead.</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="04_anova_welch_two_way_files/figure-html/histograms-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Histogram 4-cylinder vs 6-cylinder vs 8-cylinder</figcaption></figure>
</div>
</div>
</div>
<p>This histogram shows there is a difference distribution on the miles per gallon (MPG) variable between 4, 6 and 8 cylinder cars. 8 and 6 cylinder cars appear to have a normal distribution but 4 cylinder cars not.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="04_anova_welch_two_way_files/figure-html/boxplot-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Boxplot 4-cylinder vs 6 cylinder vs 8 cylinder</figcaption></figure>
</div>
</div>
</div>
<p>This boxplot also shows the difference between the three groups. 4 cylinder cars have a bigger variance on the mpg variable.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="04_anova_welch_two_way_files/figure-html/q-q-plot-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Q-Q Plots for 4-Cylinder, 6-Cylinder, and 8-Cylinder Cars</figcaption></figure>
</div>
</div>
</div>
<p>The divergence between the red line and the blue points in a Q-Q plot indicates the degree and nature of the difference between the two distributions being compared.</p>
</section><section id="assessing-skewness-and-kurtosis" class="level3" data-number="23.8.2"><h3 data-number="23.8.2" class="anchored" data-anchor-id="assessing-skewness-and-kurtosis">
<span class="header-section-number">23.8.2</span> Assessing skewness and kurtosis</h3>
<div class="cell">
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">### Assessing skewness and kurtosis</span></span>
<span><span class="co">#| label: skewness and kurtosis</span></span>
<span><span class="co">#| echo: true</span></span>
<span><span class="co">#| message: false</span></span>
<span></span>
<span><span class="co"># Calculate skewness and kurtosis for mpg_4_cyl</span></span>
<span><span class="va">skewness_4_cyl</span> <span class="op">&lt;-</span> <span class="fu">skewness</span><span class="op">(</span><span class="va">mpg_4_cyl</span><span class="op">)</span></span>
<span><span class="va">kurtosis_4_cyl</span> <span class="op">&lt;-</span> <span class="fu">kurtosis</span><span class="op">(</span><span class="va">mpg_4_cyl</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Calculate skewness and kurtosis for mpg_6_cyl</span></span>
<span><span class="va">skewness_6_cyl</span> <span class="op">&lt;-</span> <span class="fu">skewness</span><span class="op">(</span><span class="va">mpg_6_cyl</span><span class="op">)</span></span>
<span><span class="va">kurtosis_6_cyl</span> <span class="op">&lt;-</span> <span class="fu">kurtosis</span><span class="op">(</span><span class="va">mpg_6_cyl</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Calculate skewness and kurtosis for mpg_8_cyl</span></span>
<span><span class="va">skewness_8_cyl</span> <span class="op">&lt;-</span> <span class="fu">skewness</span><span class="op">(</span><span class="va">mpg_8_cyl</span><span class="op">)</span></span>
<span><span class="va">kurtosis_8_cyl</span> <span class="op">&lt;-</span> <span class="fu">kurtosis</span><span class="op">(</span><span class="va">mpg_8_cyl</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Print the results</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"Skewness for mpg_4_cyl:"</span>, <span class="va">skewness_4_cyl</span>, <span class="st">"\n"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Skewness for mpg_4_cyl: 0.2591965 </code></pre>
</div>
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"Kurtosis for mpg_4_cyl:"</span>, <span class="va">kurtosis_4_cyl</span>, <span class="st">"\n"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Kurtosis for mpg_4_cyl: -1.645012 </code></pre>
</div>
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"Skewness for mpg_6_cyl:"</span>, <span class="va">skewness_6_cyl</span>, <span class="st">"\n"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Skewness for mpg_6_cyl: -0.1583137 </code></pre>
</div>
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"Kurtosis for mpg_6_cyl:"</span>, <span class="va">kurtosis_6_cyl</span>, <span class="st">"\n"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Kurtosis for mpg_6_cyl: -1.906971 </code></pre>
</div>
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"Skewness for mpg_8_cyl:"</span>, <span class="va">skewness_8_cyl</span>, <span class="st">"\n"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Skewness for mpg_8_cyl: -0.3628186 </code></pre>
</div>
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"Kurtosis for mpg_8_cyl:"</span>, <span class="va">kurtosis_8_cyl</span>, <span class="st">"\n"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Kurtosis for mpg_8_cyl: -0.5655154 </code></pre>
</div>
</div>
<p><strong>Skewness</strong>: Skewness measures the asymmetry of the distribution of a variable. A normal distribution has a skewness value of zero, indicating symmetry. Positive skewness means the right tail is longer (values cluster to the left of the mean), while negative skewness means the left tail is longer. If skewness is substantial (<strong>e.g., greater than 2.1</strong>), it suggests departure from normality. It is not the case here!!</p>
<p><strong>Kurtosis</strong>: Kurtosis measures the peakedness of a distribution. The original kurtosis value is sometimes called “kurtosis (proper).” A normal distribution has kurtosis (proper) equal to 3. Excess kurtosis (obtained by subtracting 3 from the proper kurtosis) is often used. Substantial departure from normality occurs when excess kurtosis is <strong>greater than 7.1</strong></p>
</section><section id="normality-test" class="level3" data-number="23.8.3"><h3 data-number="23.8.3" class="anchored" data-anchor-id="normality-test">
<span class="header-section-number">23.8.3</span> Normality test</h3>
<p><strong>Shapiro-Wilk Test</strong>:</p>
<div class="cell">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Perform Shapiro-Wilk normality test</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/shapiro.test.html">shapiro.test</a></span><span class="op">(</span><span class="va">mpg_4_cyl</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  mpg_4_cyl
W = 0.91244, p-value = 0.2606</code></pre>
</div>
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/shapiro.test.html">shapiro.test</a></span><span class="op">(</span><span class="va">mpg_6_cyl</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  mpg_6_cyl
W = 0.89903, p-value = 0.3252</code></pre>
</div>
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/shapiro.test.html">shapiro.test</a></span><span class="op">(</span><span class="va">mpg_8_cyl</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  mpg_8_cyl
W = 0.93175, p-value = 0.3229</code></pre>
</div>
</div>
<p>For <strong>mpg_4_cyl</strong>: the test statistic (W = 0.91244) indicates that the data is relatively close to a normal distribution. <strong>The p-value (0.2606) is not statistically significant (above the typical threshold of 0.05).</strong> Interpretation: The data for mpg_4_cyl is not significantly different from a normal distribution. However, with small sample sizes, the test may have limited power to detect departures from normality.</p>
<p>For <strong>mpg_6_cyl</strong>: the test statistic (W = 0.89903) is slightly lower than for mpg_4_cyl but still indicates a relatively normal distribution. The p-value (0.3252) is not statistically significant (above 0.05). Interpretation: The data for mpg_6_cyl is also not significantly different from a normal distribution based on the Shapiro-Wilk test.</p>
<p>For <strong>mpg_8_cyl</strong>: the test statistic (W = 0.93175) is slightly higher than for mpg_4_cyl but still indicates a relatively normal distribution. The p-value (0.3229) is not statistically significant (above 0.05). Interpretation: The data for mpg_8_cyl is also not significantly different from a normal distribution based on the Shapiro-Wilk test.</p>
<p><strong>Again, note that with small sample sizes, the ability to detect deviations from normality may be limited.</strong> Small sample sizes can limit the power of statistical tests to detect departures from normality, and it’s important to consider the context and potential limitations when interpreting such results.</p>
</section></section><section id="performing-the-welchs-anova" class="level2" data-number="23.9"><h2 data-number="23.9" class="anchored" data-anchor-id="performing-the-welchs-anova">
<span class="header-section-number">23.9</span> Performing the Welchs Anova</h2>
<p>We will perform a Welch’s Anova to compare the mean miles per gallon (mpg) between cars with 4 cylinders, with 6 cylinders and with 8 cylinders cars.</p>
<p>Hypotheses Null Hypothesis (H0): The mean mpg of cars with 4 cylinders, 6 cylinders and 8 cylinders is equal. Alternative Hypothesis (H1): The mean mpg of cars with 4 cylinders, 6 cylinders and 8 cylinders is not equal.</p>
<section id="welchs-anova-results" class="level3" data-number="23.9.1"><h3 data-number="23.9.1" class="anchored" data-anchor-id="welchs-anova-results">
<span class="header-section-number">23.9.1</span> Welchs Anova results</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    One-way analysis of means (not assuming equal variances)

data:  mpg and cylinders
F = 31.624, num df = 2.000, denom df = 18.032, p-value = 1.271e-06</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code> cylinders emmean    SE df lower.CL upper.CL
 4           26.7 0.972 29     24.7     28.7
 6           19.7 1.218 29     17.3     22.2
 8           15.1 0.861 29     13.3     16.9

Confidence level used: 0.95 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast                estimate   SE df t.ratio p.value
 cylinders4 - cylinders6     6.92 1.56 29   4.441  0.0003
 cylinders4 - cylinders8    11.56 1.30 29   8.905  &lt;.0001
 cylinders6 - cylinders8     4.64 1.49 29   3.112  0.0112

P value adjustment: tukey method for comparing a family of 3 estimates </code></pre>
</div>
</div>
</section><section id="interpretation-or-results" class="level3" data-number="23.9.2"><h3 data-number="23.9.2" class="anchored" data-anchor-id="interpretation-or-results">
<span class="header-section-number">23.9.2</span> Interpretation or results:</h3>
<p>F-Value: The test statistic for the Welch’s ANOVA. num df: The degrees of freedom for the numerator. denom df: The degrees of freedom for the denominator. p-value: The p-value for the test. A small p-value (typically &lt; 0.05) indicates that there are significant differences between the group means.</p>
<p>• *<strong>F-Statistic:</strong> 31.624 • <strong>Numerator Degrees of Freedom:</strong> 2.000 • <strong>Denominator Degrees of Freedom:</strong> 18.032 • <strong>P-Value:</strong> 1.271×10−6.</p>
<p>The extremely low p-value indicates that there is a statistically significant difference in the mean MPG across the three groups of cars (4-cylinder, 6-cylinder, and 8-cylinder).</p>
<div class="callout-Note">
<p><strong>Estimated Marginal Means (MPG) for Each Cylinder Group</strong></p>
<table class="table">
<thead><tr class="header">
<th>Cylinders</th>
<th>EMM</th>
<th>SE</th>
<th>df</th>
<th>Lower CI</th>
<th>Upper CI</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>4</td>
<td>26.7</td>
<td>0.972</td>
<td>29</td>
<td>24.7</td>
<td>28.7</td>
</tr>
<tr class="even">
<td>6</td>
<td>19.7</td>
<td>1.218</td>
<td>29</td>
<td>17.3</td>
<td>22.2</td>
</tr>
<tr class="odd">
<td>8</td>
<td>15.1</td>
<td>0.861</td>
<td>29</td>
<td>13.3</td>
<td>16.9</td>
</tr>
</tbody>
</table>
<p><strong>Interpretation</strong>: - The average MPG for 4-cylinder cars is 26.7. - The average MPG for 6-cylinder cars is 19.7. - The average MPG for 8-cylinder cars is 15.1.</p>
<p>These intervals do not overlap, suggesting clear differences in the mean MPG across the different cylinder groups.</p>
</div>
<div class="callout-Note">
<p><strong>Pairwise Comparisons of Mean MPG</strong></p>
<table class="table">
<colgroup>
<col style="width: 39%">
<col style="width: 15%">
<col style="width: 9%">
<col style="width: 6%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead><tr class="header">
<th>Contrast</th>
<th>Estimate</th>
<th>SE</th>
<th>df</th>
<th>t-ratio</th>
<th>p-value</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>4 Cylinders - 6 Cylinders</td>
<td>6.92</td>
<td>1.56</td>
<td>29</td>
<td>4.441</td>
<td>0.0003</td>
</tr>
<tr class="even">
<td>4 Cylinders - 8 Cylinders</td>
<td>11.56</td>
<td>1.30</td>
<td>29</td>
<td>8.905</td>
<td>&lt;.0001</td>
</tr>
<tr class="odd">
<td>6 Cylinders - 8 Cylinders</td>
<td>4.64</td>
<td>1.49</td>
<td>29</td>
<td>3.112</td>
<td>0.0112</td>
</tr>
</tbody>
</table>
<p><strong>Interpretation</strong>: - <strong>4 Cylinders vs.&nbsp;6 Cylinders</strong>: The mean difference in MPG is 6.92, which is statistically significant (( p = 0.0003 )). - <strong>4 Cylinders vs.&nbsp;8 Cylinders</strong>: The mean difference in MPG is 11.56, which is highly statistically significant (( p &lt; 0.0001 )). - <strong>6 Cylinders vs.&nbsp;8 Cylinders</strong>: The mean difference in MPG is 4.64, which is statistically significant (( p = 0.0112 )).</p>
<p>All these differences are statistically significant, indicating that the MPG for 4-cylinder cars is significantly higher than for 6-cylinder and 8-cylinder cars, and the MPG for 6-cylinder cars is significantly higher than for 8-cylinder cars.</p>
</div>
<div class="callout callout-style-simple callout-important">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>Mean:</strong> The mean is a basic measure of central tendency. It represents the arithmetic average of a set of values. It provides a single value that summarizes the data distribution. However, it doesn’t account for other factors or covariates.</p>
<p><strong>Estimated Marginal Mean (EMM):</strong> EMMs are adjusted means that consider other variables in the model. They account for the effects of covariates, making them more informative. EMMs are useful when comparing treatment levels in complex models. For example, in an ANOVA with interactions or mixed-effects models, EMMs provide adjusted group means. EMMs help address confounding and provide a clearer picture of treatment effects. <strong>In summary</strong>, while the mean is straightforward and unadjusted, EMMs offer a more nuanced understanding by considering covariates.</p>
</div>
</div>
</div>
<p><strong>Conclusion</strong></p>
<p>The analysis shows that there are significant differences in the mean MPG between cars with different numbers of cylinders. Specifically, 4-cylinder cars have the highest mean MPG, followed by 6-cylinder cars, and then 8-cylinder cars. The pairwise comparisons confirm that all these differences are statistically significant, with the 4-cylinder cars performing significantly better in terms of fuel efficiency compared to both 6-cylinder and 8-cylinder cars.</p>
</section></section><section id="satterthwaite-degrees-of-freedom" class="level2" data-number="23.10"><h2 data-number="23.10" class="anchored" data-anchor-id="satterthwaite-degrees-of-freedom">
<span class="header-section-number">23.10</span> Satterthwaite Degrees of Freedom</h2>
<p>In the context of Welch’s t-test and Welchs Anova, the Satterthwaite approximation is used to calculate an approximation of the degrees of freedom. This method provides a more accurate estimation compared to the standard t-test and traditional Anova when the variances of the two samples are not equal.</p>
<p>The formula for the Satterthwaite degrees of freedom is: <span class="math display">\[
\nu \approx \frac{\left( \frac{s_1^2}{n_1} + \frac{s_2^2}{n_2} \right)^2}{\frac{\left( \frac{s_1^2}{n_1} \right)^2}{n_1 - 1} + \frac{\left( \frac{s_2^2}{n_2} \right)^2}{n_2 - 1}}
\]</span></p>
<p>Where: <span class="math display">\[ s_1^2 \]</span> is the sample variance of the first sample (4-cylinder cars), <span class="math display">\[ s_2^2 \]</span> is the sample variance of the second sample (6-cylinder cars), <span class="math display">\[ n_1 \]</span> is the sample size of the first sample (4-cylinder cars) and <span class="math display">\[ n_2 \]</span> is the sample size of the second sample (6-cylinder cars).</p>
<div class="cell">
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Sample sizes</span></span>
<span><span class="va">n1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">mpg_4_cyl</span><span class="op">)</span></span>
<span><span class="va">n2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">mpg_6_cyl</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Sample variances</span></span>
<span></span>
<span><span class="va">s1_sq</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/cor.html">var</a></span><span class="op">(</span><span class="va">mpg_4_cyl</span><span class="op">)</span></span>
<span><span class="va">s2_sq</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/cor.html">var</a></span><span class="op">(</span><span class="va">mpg_6_cyl</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Satterthwaite degrees of freedom</span></span>
<span><span class="va">numerator</span> <span class="op">&lt;-</span> <span class="op">(</span><span class="va">s1_sq</span> <span class="op">/</span> <span class="va">n1</span> <span class="op">+</span> <span class="va">s2_sq</span> <span class="op">/</span> <span class="va">n2</span><span class="op">)</span><span class="op">^</span><span class="fl">2</span></span>
<span><span class="va">denominator</span> <span class="op">&lt;-</span> <span class="op">(</span><span class="op">(</span><span class="va">s1_sq</span> <span class="op">/</span> <span class="va">n1</span><span class="op">)</span><span class="op">^</span><span class="fl">2</span> <span class="op">/</span> <span class="op">(</span><span class="va">n1</span> <span class="op">-</span> <span class="fl">1</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> <span class="op">(</span><span class="op">(</span><span class="va">s2_sq</span> <span class="op">/</span> <span class="va">n2</span><span class="op">)</span><span class="op">^</span><span class="fl">2</span> <span class="op">/</span> <span class="op">(</span><span class="va">n2</span> <span class="op">-</span> <span class="fl">1</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">df</span> <span class="op">&lt;-</span> <span class="va">numerator</span> <span class="op">/</span> <span class="va">denominator</span></span>
<span></span>
<span><span class="co"># Print the result</span></span>
<span><span class="va">df</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 12.95598</code></pre>
</div>
</div>
<section id="degrees-of-freedom-dof-explanation" class="level3" data-number="23.10.1"><h3 data-number="23.10.1" class="anchored" data-anchor-id="degrees-of-freedom-dof-explanation">
<span class="header-section-number">23.10.1</span> Degrees of Freedom (DoF) explanation:</h3>
<p>The <strong>degrees of freedom</strong> indicate the number of independent values or quantities which can vary in the analysis without breaking any constraints. In this context, the degrees of freedom are adjusted to better reflect the reliability of the variance estimates from the samples <span class="citation" data-cites="Huang2016-dp">(<a href="#ref-Huang2016-dp" role="doc-biblioref">Huang, 2016</a>)</span>.</p>
<p><strong>Satterthwaite Approximation:</strong> this method provides an adjusted degrees of freedom value that accounts for differences in variances between the samples. The formula combines the sample variances and sizes to compute a more accurate degrees of freedom for the Welch’s t-test and Welchs Anova.</p>
<p><strong>Implications:</strong> using the Satterthwaite approximation leads to a more robust test when comparing means from two samples with unequal variances. The resulting degrees of freedom are used to determine the critical value from the t-distribution, which is crucial for calculating the p-value and making statistical inferences <span class="citation" data-cites="Derrick2016-wq">(<a href="#ref-Derrick2016-wq" role="doc-biblioref">Derrick, Toher, &amp; White, 2016</a>)</span>.</p>
<p><strong>Degrees of Freedom Calculation for the two sample t-test:</strong> can be calculated as follows:</p>
<p><span class="math display">\[
\text{DoF} = (n_1 - 1) + (n_2 - 1) = (n_1 + n_2 - 2)
\]</span></p>
<p>Where: <span class="math display">\[ n_1 \]</span> is the number of observations in the first group. <span class="math display">\[ n_2 \]</span> is the number of observations in the second group.</p>
<p><strong>Why Subtract the Number of Groups?:</strong></p>
<p>We subtract 2 because we are estimating one parameter (the mean) for each of the two groups. Each estimation reduces the degrees of freedom by 1. Thus, for two groups, we subtract 2 from the total number of observations to account for the two estimated means.</p>
<p><strong>Satterthwaite vs t-test degrees of freedom:</strong></p>
<p>Calculated Degrees of Freedom using the Satterthwaite method: approximately 18</p>
<p>Traditional t-test Degrees of Freedom: n1+n2+n3-3=11+7+14-3=29</p>
<p>The Satterthwaite degrees of freedom (18) are lower than the traditional degrees of freedom (29). This adjustment accounts for the unequal variances between the three samples (4-cylinder, 6-cylinder cars and 8-cylinder cars) and provides a more accurate measure for the t-distribution used in the Welch’s t-test and Welchs Anova.</p>
</section><section id="important-concepts-about-the-degrees-of-freedom" class="level3" data-number="23.10.2"><h3 data-number="23.10.2" class="anchored" data-anchor-id="important-concepts-about-the-degrees-of-freedom">
<span class="header-section-number">23.10.2</span> Important concepts about the degrees of Freedom</h3>
<div class="note">
<h3 class="anchored">
Degrees of Freedom (DoF)
</h3>
<p>
Represent the number of independent values that can vary without breaking constraints.
</p>
<h3 class="anchored">
Traditional t-Test and Traditional Anova
</h3>
<p>
DoF is the total number of observations minus the number of groups because each group’s mean estimation uses one degree of freedom.
</p>
<h3 class="anchored">
Satterthwaite Approximation
</h3>
<p>
Adjusts the DoF for unequal variances, usually resulting in a lower and non-integer value, providing a more accurate basis for hypothesis testing.
</p>
</div>
<style>
.note {
  padding: 10px;
  background-color: #f9f9f9;
  border: 2px solid green; /* Green border around all sides */
  max-width: 400px; /* Limit the width of the box */
  margin: 20px 0; /* Space around the box */
  animation: moveBox 2s linear infinite; /* Continuous animation */
  position: relative;
}

/* Keyframes for continuous animation */
@keyframes moveBox {
  0% { left: 0; }
  50% { left: 20px; }
  100% { left: 0; }
}
</style></section></section><section id="summary-and-conclusion" class="level2" data-number="23.11"><h2 data-number="23.11" class="anchored" data-anchor-id="summary-and-conclusion">
<span class="header-section-number">23.11</span> Summary and Conclusion</h2>
<p>Welch’s Anova, useful for comparing means of three independent samples with unequal variances and sizes, was applied to the mtcars dataset to compare 4-cylinder, 6-cylinder and 8-cylinder cars MPG. The test revealed a significant difference in means, with a p-value of 0.000001271, rejecting the null hypothesis. The Satterthwaite approximation, yielding degrees of freedom at 18, provided a more accurate assessment than the traditional t-test (DoF = 29), ensuring robust statistical inference under unequal variances. This method enhances reliability, especially with large samples, where normality is approached due to the Central Limit Theorem.</p>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-Delacre2019-ra" class="csl-entry" role="listitem">
Delacre, M., Leys, C., Mora, Y. L., &amp; Lakens, D. (2019). Taking parametric assumptions seriously: Arguments for the use of welch’s f-test instead of the classical f-test in one-way <span>ANOVA</span>. <em>International Review of Social Psychology</em>, <em>32</em>(1).
</div>
<div id="ref-Derrick2016-wq" class="csl-entry" role="listitem">
Derrick, B., Toher, D., &amp; White, P. (2016). Why welch’s test is type <span>I</span> error robust. The quantitative methods for. <em>Psychology</em>, <em>12</em>(1), 30–38.
</div>
<div id="ref-Huang2016-dp" class="csl-entry" role="listitem">
Huang, H. (2016). On the <span>Welch-Satterthwaite</span> formula for uncertainty estimation: A paradox and its resolution. <em>Cal Lab the International Journal of Metrology</em>, <em>23</em>(4), 20–28.
</div>
<div id="ref-Kwak2017-vr" class="csl-entry" role="listitem">
Kwak, S. G., &amp; Kim, J. H. (2017). Central limit theorem: The cornerstone of modern statistics. <em>Korean J. Anesthesiol.</em>, <em>70</em>(2), 144–156.
</div>
<div id="ref-Labovitz2017-yp" class="csl-entry" role="listitem">
Labovitz, S. (2017). Criteria for selecting a significance level:: A note on the sacredness of. 05. In <em>The significance test controversy</em> (pp. 166–171).
</div>
<div id="ref-Liu2015-xy" class="csl-entry" role="listitem">
Liu, H. (2015a). <em>Comparing welch <span>ANOVA</span>, a <span>Kruskal-Wallis</span> test, and traditional <span>ANOVA</span> in case of heterogeneity of variance</em>.
</div>
<div id="ref-Liu2015-ql" class="csl-entry" role="listitem">
Liu, H. (2015b). <em>Comparing welch <span>ANOVA</span>, a <span>Kruskal-Wallis</span> test, and traditional <span>ANOVA</span> in case of heterogeneity of variance</em>.
</div>
<div id="ref-Razali2011-aq" class="csl-entry" role="listitem">
Razali, N. M., &amp; Wah, Y. B. (2011). Power comparisons of shapiro-wilk, kolmogorov-smirnov, lilliefors and anderson-darling tests. <em>Journal of Statistical Modeling and Analytics</em>, <em>2</em>(1), 21–33.
</div>
<div id="ref-ruxton2006unequal" class="csl-entry" role="listitem">
Ruxton, G. D. (2006). The unequal variance t-test is an underused alternative to student’s t-test and the mann–whitney u test. <em>Behavioral Ecology</em>, <em>17</em>(4), 688–690. <a href="https://doi.org/10.1093/beheco/ark016">https://doi.org/10.1093/beheco/ark016</a>
</div>
</div>
</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/gabrielodom\.github\.io\/PHC6099_rBiostat\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="../lessons/04_anova_two_way.html" class="pagination-link" aria-label="Two-Way ANOVA">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Two-Way ANOVA</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../lessons_original/04_anova_kruskal_wallis.html" class="pagination-link" aria-label="Non-Parametric ANOVA: The Kruskal-Wallis Test">
        <span class="nav-page-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Non-Parametric ANOVA: The Kruskal-Wallis Test</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/gabrielodom/PHC6099_rBiostat/edit/main/lessons/04_anova_welch_two_way.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/gabrielodom/PHC6099_rBiostat/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>This book was built with <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>


</body></html>